# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoCATer
                                 A QGIS plugin
 Plugin to calculate EOO and AOO for species threat status in conservation studies 
 Generated by Plugin Builder: http: // g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-01
        copyright            : (C) 2024 by Diego Sousa Campos
        email                : diegosousa.campos@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoCATer class from file GeoCATer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geocater import GeoCATer
    return GeoCATer(iface)
